# Site settings
title: Universal Ramblings
index_title: Damian Dailisan # same as title in index.html file, so that custom description can be set in page.html layout.
blog_title: Damian Dailisan
header-img: img/home-bg.jpg
author: "Damian Dailisan"
email: damian.dailisan@gmail.com
copyright_name: damian.dailisan
description: "A cornucopia of code used for physics classes."
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url: http://temetski.github.io #only used in disque comments for now
github_username:  temetski
facebook_username:  damian.dailisan
email_username:  damian.dailisan@gmail.com
google_analytics: G-B7FP4W3KF7
# used to estimate reading time
wpm: 180

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "*.ipynb"]
port: 4000
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-redirect-from, jekyll-sitemap]
